"""Initial migration

Revision ID: b2ccadaae1d1
Revises: 
Create Date: 2024-11-02 03:03:20.316128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2ccadaae1d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('data_cadastro', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data_compra', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id_cliente', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('id_categoria', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalhe_pedidos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_pedido', sa.UUID(), nullable=False),
    sa.Column('id_produto', sa.UUID(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_produto'], ['produtos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalhe_pedidos')
    op.drop_table('produtos')
    op.drop_table('pedidos')
    op.drop_table('usuarios')
    op.drop_table('clientes')
    op.drop_table('categorias')
    # ### end Alembic commands ###
